### PR TITLE
Added tutorials to site

### PR DESCRIPTION
**Pull request by julienvillegas**
added tutorials

### CODE REVIEW

**Comment by Tom-Ski** [comment]
A lot of these tutorials posted have questionable material, and guide people into common pitfalls, so they will not be present on the site.

**Comment by julienvillegas** [comment]
ok, thanks.

**Comment by julienvillegas** [comment]
Alhough to be honest, I was trying to help someone junior  get started with libgdx and came to the realisation that it is quite abrupt. Framework is quite mature but we need to ease new starter's journey and also showcase some beautiful games. I think that's the part that requires focus to dynamize and renew the community. Sorry for the rant, I know it is not the place.. love LibGDX, happy to help when and where I can

**Comment by Tom-Ski** [comment]
Your contributions are very welcome. I do aim to write the articles myself when I can, most of the tutorials for 2D out there are just not good enough for us to recommend to people.  I have started on some essentials tutorials, and I'd like to get some feedback from the community as to what tutorials they would want as a priority.

**Pull request closed without merging**
